### ISSUE TITLE
Building of ThinkSpiceFood API architecture

### ISSUE THREAD

**Issue by chibuike07** [BuildForSDGCohort2/team-086-group-a-backend#2]
ThinkSpiceFood Architecture

**Comment by Tboy-AK** [comment]
I will send this in, later in the evening.

**Comment by Tboy-AK** [comment]
I have sent the database model to the Slack group https://buildforsdgcohort2.slack.com/archives/C018T711GMR/p1598751471000900

**Comment by chibuike07** [comment]
Thanks for the awesome work
