### ISSUE TITLE
view/work on the method/design of registration of users in the ThinkSpiceFood

### ISSUE THREAD

**Issue by chibuike07** [BuildForSDGCohort2/team-086-group-a-backend#4]

**Comment by Tboy-AK** [comment]
Will there be Google and Facebook login?

**Comment by chibuike07** [comment]
Yes there will be @Myspheet and @Basifrank also take note please.

**Comment by chibuike07** [comment]
please we have not heard from you all on this issue. what is the challenge, please

**Comment by Myspheet** [comment]
What do you mean view/work on the method/design

**Comment by chibuike07** [comment]
I mean the architecture / the models, though @Tboy-AK @SenJames added it in the chart he showed, I was thinking you guys would come out with the registration section of the app too. But are you guys cool with the chart we have.
