### ISSUE TITLE
building of the project models

### ISSUE THREAD

**Issue by chibuike07** [BuildForSDGCohort2/team-086-group-a-backend#5]
@SenJames please work with this team to see if you can integrate very well with nodejs, thanks.

**Comment by Tboy-AK** [comment]
I suppose I already created the models. Except there are things the team members want to include [here](https://buildforsdgcohort2.slack.com/archives/C018T711GMR/p1598751471000900?thread_ts=1598751471.000900&cid=C018T711GMR). Shouldn't we be moving to a new issue

**Comment by chibuike07** [comment]
Please @Tboy-AK  browser about mongoose schema to understand what you are to do with the architecture you did earlier, thanks

**Comment by HENRYKC24** [comment]
Please what am i expected to do in this backend? i understand mogoose schema but i don't know how to get started. what aspect am i working on?

**Comment by chibuike07** [comment]
now, I think I have to build the auth schema to show an example

**Comment by jobizil** [comment]
> Please what am i expected to do in this backend? i understand mogoose schema but i don't know how to get started. what aspect am i working on?

Hello @HENRYKC24 have you been able to fix your mongoose Schema stuff or you need some help?

**Comment by HENRYKC24** [comment]
I need a call. Whatsapp call will be good so i have a good understanding of what i am assigned to do
